### PR TITLE
Upgrade Hadoop to support AWS Web Identity authentication method

### PR DESCRIPTION
**Pull request by zanitete**
needed by IRSA to assume a Role using the OIDC token provided by Kubernetes

aws-sdk version needed: [1.11.704](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html)
hadoop 3.2.4 provides [1.11.901](https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/3.2.4)

### CODE REVIEW

**Comment by zanitete** [comment]
already pushed to Nexus as spark-3.0.0-ni.2-bin-without-hadoop.tgz

**Review by smrtl — APPROVED** [review]
👍

**Review by AWebNagra — APPROVED** [review]

**Comment by zanitete** [comment]
not working, closing

**Pull request closed without merging**
